// Converts the points generated by perfect-freehand into an SVG path string
export function getSvgPathFromStroke(stroke) {
  if (!stroke.length) return ""; // If no stroke points, return an empty string

  // Generate path data by creating a quadratic curve between each point
  const d = stroke.reduce(
    (acc, [x0, y0], i, arr) => {
      const [x1, y1] = arr[(i + 1) % arr.length]; // Get the next point
      acc.push(x0, y0, (x0 + x1) / 2, (y0 + y1) / 2); // Create a midpoint between the points
      return acc;
    },
    ["M", ...stroke[0], "Q"] // Move to the first point and start the quadratic curve
  );

  d.push("Z"); // Close the path
  return d.join(" "); // Return the generated SVG path as a string
}